In [ ]:
import pandas as pd
import dask.dataframe as df
import sqlalchemy as sq
import requests
import kagglehub
import psycopg2
import numpy as np
import json
import glob
import os
import zipfile as zf

In [ ]:



Data_2011 = pd.read_csv('SourceData/2011.csv')

In [20]:
#Dropping columns that are either all NA, NaN or are not in the CDC codes
Data_2011.drop(columns=['_DENSTR2', 'PRECALL', 'REPNUM', 'REPDEPTH', 'HAVHPAD','_GEOSTR'], axis = 1, inplace=True)
Data_2011.drop(columns=['FMONTH', 'DISPCODE','CTELENUM', 'NUMADULT', 'NUMWOMEN', 'CTELNUM1', 'CELLFON2',
'IYEAR', 'NUMMEN'], axis = 1, inplace = True)
Data_2011.head()

,_STATE,IDATE,IMONTH,IDAY,INTVID,SEQNO,_PSU,NATTMPTS,NRECSEL,NRECSTR,...,_PNEUMO2,DRNKANY5,DROCDY3_,_RFBING5,_DRNKDY4,_DRNKMO4,_RFDRHV4,_RFDRMN4,_RFDRWM4,_AIDTST3
0,1.0,b'01202011',b'01',b'20',b'00118',2.011000e+09,2.011000e+09,6.0,1662.0,56365.0,...,NaN,1.0,4.300000e+01,1.0,8.600000e+01,2.600000e+01,1.0,NaN,1.0,2.0
1,1.0,b'01142011',b'01',b'14',b'00136',2.011000e+09,2.011000e+09,6.0,1662.0,56365.0,...,NaN,9.0,9.000000e+02,9.0,9.900000e+03,9.999000e+03,9.0,9.0,NaN,NaN
2,1.0,b'01062011',b'01',b'06',b'00140',2.011001e+09,2.011001e+09,1.0,1689.0,113769.0,...,9.0,1.0,1.400000e+01,1.0,1.400000e+01,4.000000e+00,1.0,NaN,1.0,2.0
3,1.0,b'02012011',b'02',b'01',b'00188',2.011001e+09,2.011001e+09,15.0,2088.0,41627.0,...,9.0,9.0,9.000000e+02,9.0,9.900000e+03,9.999000e+03,9.0,NaN,9.0,NaN
4,1.0,b'02012011',b'02',b'01',b'00118',2.011001e+09,2.011001e+09,14.0,2088.0,41627.0,...,NaN,2.0,5.397605e-79,1.0,5.397605e-79,5.397605e-79,1.0,NaN,1.0,1.0

In [16]:
#Updating NaN values to 9.0 for unknown, NaN represent questions that were not asked or missing. If they are questions relating to a specific gender, they will be dropped accordingly.
Data_2011.fillna(value=9.0, inplace=True)

,_STATE,IDATE,IMONTH,IDAY,INTVID,SEQNO,_PSU,NATTMPTS,NRECSEL,NRECSTR,...,_PNEUMO2,DRNKANY5,DROCDY3_,_RFBING5,_DRNKDY4,_DRNKMO4,_RFDRHV4,_RFDRMN4,_RFDRWM4,_AIDTST3
0,1.0,b'01202011',b'01',b'20',b'00118',2.011000e+09,2.011000e+09,6.0,1662.0,56365.0,...,9.0,1.0,4.300000e+01,1.0,8.600000e+01,2.600000e+01,1.0,9.0,1.0,2.0
1,1.0,b'01142011',b'01',b'14',b'00136',2.011000e+09,2.011000e+09,6.0,1662.0,56365.0,...,9.0,9.0,9.000000e+02,9.0,9.900000e+03,9.999000e+03,9.0,9.0,9.0,9.0
2,1.0,b'01062011',b'01',b'06',b'00140',2.011001e+09,2.011001e+09,1.0,1689.0,113769.0,...,9.0,1.0,1.400000e+01,1.0,1.400000e+01,4.000000e+00,1.0,9.0,1.0,2.0
3,1.0,b'02012011',b'02',b'01',b'00188',2.011001e+09,2.011001e+09,15.0,2088.0,41627.0,...,9.0,9.0,9.000000e+02,9.0,9.900000e+03,9.999000e+03,9.0,9.0,9.0,9.0
4,1.0,b'02012011',b'02',b'01',b'00118',2.011001e+09,2.011001e+09,14.0,2088.0,41627.0,...,9.0,2.0,5.397605e-79,1.0,5.397605e-79,5.397605e-79,1.0,9.0,1.0,1.0

In [32]:

Data_2015 = pd.read_csv('SourceData/2015.csv')

In [34]:
#Data_2012.head()
#Data_2013.head()

Data_2015.fillna(value=9.0, inplace=True)